pring.application.name=campusFlow

# Base de datos (lee las variables de Render, si no existen usa local)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/campus}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:maicolpro123}

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto del servidor
server.port=${PORT:8080}

# Configuración Stripe
stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:whsec_pendiente}
stripe.price-pago-unico=${STRIPE_PRICE_PAGO_UNICO}
stripe.price-plan-individual=${STRIPE_PRICE_PLAN_INDIVIDUAL}
stripe.url-exito=${STRIPE_URL_EXITO:http://localhost:8080/pago-exitoso}
stripe.url-cancelado=${STRIPE_URL_CANCELADO:http://localhost:8080/pago-cancelado}